#45장 프로미스
=================================================================

- 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 `콜백 함수`를 사용함
  - 콜백 패턴 : 콜백 헬로 인해 `가독성 나쁘고` + `에러 처리 곤란` + 여러 개의 비동기 처리를 `한 번에 처리할 때 한계 O`
- ES6 : 비동기 처리를 위한 또 다른 패턴 프로미스(Promise) 도입
  - 전통적인 `콜백 패턴이 가진 단점 보완` + `비동기 처리 시점을 명확하게 표현`할 수 있다는 장점


# 45-1. 비동기 처리를 위한 콜백 패턴의 단점

## 45-1-1. 콜백 헬

````javascript
// GET 요청을 위한 비동기 함수
const get = url => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();
    
    xhr.onload = () => {
        if (xhr.status === 200) {
            // 서버의 응답을 콘솔에 출력
            console.log(JSON.parse(xhr.response));
        } else {
            console.error(`${xhr.status} ${xhr.statusText}`);
        }
    };
};

// id 가 1인 post 를 취득
get('https://jsonplaceholder.typicode.com/posts/1');

/*
{
 "userId": 1,
 "id": 1,
 "title": "sunt aut facere ...",
 "body": "quia et suscipit ..."
}
*/
````

- get 함수 : 비동기 함수
- 비동기 함수 : 함수 내부에 비동기로 동작하는 코드를 포함한 함수

#### 비동기 함수를 `호출`하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도, 기다리지 않고 `즉시 종료`됨
#### 즉, `비동기 함수 내부의 비동기로 동작하는 코드`는 `비동기 함수가 종료된 이후에 완료`됨
#### so, `비동기 함수 내부의 비동기로 동작하는 코드`에서 `처리 결과를 외부로 반환`하거나, `상위 스코프의 변수에 할당`하면 기대한 대로 `동작 X`

예를 들어,
- setTimeout 함수 = 비동기 함수
  - 콜백 함수의 호출이 비동기로 동작하기 때문
  - setTimeout 을 호출하면, 콜백 함수를 호출 스케줄링한 다음, 타이머 id 를 반환 + 즉시 종료
- 즉, 비동기 함수인 setTimeout 함수의 콜백 함수는 setTimeout 함수가 종료된 이후에 호출됨
- so, setTimeout 함수 내부의 콜백 함수에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작 X


- setTimeout 함수의 콜백 함수에서 상위 스코프에 변수의 값을 할당해보자
- setTimeout 함수는 생성된 타이머를 식별할 수 있는 고유한 타이머 id 를 반환하므로 콜백 함수에서 값을 반환하는 것은 무의미


```javascript
let g = 0;

// 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당 X
setTimeout(() => { g = 100 }, 0);
console.log(g); // 0
```

### get 함수
- `비동기 함수`
- GET 요청을 전송하고 서버의 응답을 전달받음
- 비동기 함수인 이유
  - get 함수 내부의 `onload 이벤트 핸들러가 비동기로 동작`하기 때문
- `호출`하면 GET 요청을 전송하고 `onload 이벤트 핸들러를 등록`한 다음 + `undefined 를 반환` + 즉시 종료
  - so, get 함수의 onload 이벤트 핸들러에서,
  - 서버의 응답 결과를 반환하거나 상위 스코프의 변수에 할당하면 제대로 동작 X


get 함수가 서버의 응답 결과를 반환하도록 수정해 보자

```javascript
// GET 요청을 위한 비동기 함수
const get = url => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();
    
    xhr.onload = () => {
        if (xhr.status === 200) {
            // 1. 서버의 응답을 반환
          return JSON.parse(xhr.response);
        }
        console.error(`${xhr.status} ${xhr.statusText}`);
    };
};

// 2. id 가 1 인 post 를 취득
const response = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response);  // unedfined 반환 :: 명시적인 반환문이 없으므로
```

- get 함수가 호출되면 XMLHttpRequest 객체를 생성 + HTTP 요청 초기화 + HTTP 요청 전송
- xhr.onload 이벤트 프로퍼티에 이벤트 핸들러를 바인딩 + 종료
  - 이때 get 함수에 명시적인 반환문이 없으므로, `get 함수는 undefined 를 반환함(2)`


- xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문(1)
  - get 함수의 반환문 X
  - 암묵적으로 undefined 를 반환
- `함수의 반환값은 명시적으로 호출한 다음에 캐치할 수 있으므로`,
  - onload 이벤트 핸들러를 get 함수가 호출할 수 있다면
  - 이벤트 핸들러의 반환값을 get 함수가 캐치하여 다시 반환할 수도 있겠지만
  - onload 이벤트 핸들러는 get 함수가 호출하지 않기 때문에 그럴 수도 X


- 서버로부터 응답이 xhr 객체에서 load 이벤트가 발생함
#### 이때 xhr.onload 핸들러 프로퍼티에 바인딩한 `이벤트 핸들러가 즉시 실행되는 것이 X`
#### xhr.onload 이벤트 핸들러는 load 이벤트가 발생하면 일단 `태스크 큐에 저장되어 대기`하다가,
#### `콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행됨`


#### 이처럼 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수 X
#### so, `비동기 함수의 처리 결과(서버의 응답 등)` 에 대한 후속 처리는 `비동기 함수 내부에서 수행`해야 함
#### 이때 비동기 함수를 범용적으로 사용하기 위해, 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 `콜백 함수를 전달하는 것이 일반적`임
#### 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면, 호출될 콜백 함수를 전달할 수 있음

- 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출
  - `콜백 헬(callback hell)`
  - 콜백 함수 호출이 `중첩`되어 복잡도가 높아지는 현상

## 45-1-2. 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것 : 에러 처리가 곤란하다는 것

```javascript
try {
    setTimeout(() => { throw new Error('Error!') }, 1000 );
} catch (e) {
    // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e)
}
```

> [ try ... catch ... finally 문 ]
> - 에러 처리를 구현하는 방법
> - 이 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.


#### 에러는 호출자(caller) 방향으로 전파됨

- 즉, `콜 스택의 아래 방향`(실행 중인 실행 컨텍스트가 푸시되기 `직전에 푸시된 실행 컨텍스트 방향`) 으로 전파됨
- but, setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수 X
  - so, `setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 X`

# 45-2. 프로미스의 생성

- `Promise 생성자 함수`를 new 연산자와 함께 호출하면 `프로미스(Promise 객체)` 를 생성
- ES6 에서 도입된 Promise 는 호스트 객체가 아닌 `ECMAScript 사양에 정의된 표준 빌트인 객체`



### Promise 생성자 함수
  - 비동기 처리를 수행할 `콜백 함수`(ECMAScript 사양에서는 executor 함수라고 부름) 를 인수로 전달받음
    - 이 콜백 함수는 r`esolve 와 reject 함수를 인수로 전달받음`

```javascript
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
    // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행함
  if (/* 비동기 처리 성공*/) {
      resolve('result');
  } else (/* 비동기 처리 실패*/) {
      reject('failure reason');
  }
});
```

앞에서 살펴본 비동기 함수 get 을 프로미스를 사용해 구현해보자

````javascript
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.send();
        
        xhr.onload = () => {
            if (xhr.status === 200) {
                resolve(JSON.parse(xhr.response));
            } else {
                reject(new Error(xhr.status));
            }
        };
    });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1');
````

| 프로미스의 상태 정보 | 의미                    | 상태 변경 조건           |
|:------------|:----------------------|:-------------------|
| pending     | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |          
| fulfilled   | 비동기 처리가 수행된 상태(성공)    | resolve 함수 호출      | 
| rejected    | 비동기 처리가 수행된 상태(실패)    | reject 함수 호출       |


비동기 처리 성공
: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경

비동기 처리 실패
: reject 함수를 호출해 프로미스를 reject 상태로 변경

#### 프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정됨

settled 상태
- fulfilled 또는 rejected 상태
- pending 이 아닌 상태로, 비동기 처리가 수행된 상태

프로미스
- pending 상태에서 fulfilled 또는 rejected 상태, 즉 settled 상태로 변화 O
- but, 일단 settled 상태가 되면 다른 상태로 변화 X
- 비동기 처리 상태 + 비동기 처리결과를 상태로 가짐

````javascript
// fulfilled 된 프로미스
const fulfilled = new Promise(resolve => resolve(1));
````

비동기 처리가 성공하면 프로미스는 pending 상태에서 fulfilled 상태로 변화함 + 비동기 처리 결과인 1을 값으로 가짐

```javascript
// rejected 된 프로미스
const rejected = new Promise((_, reject) => reject(new Error('error occurred')));
```

비동기 처리가 성공하면 프로미스는 pending 상태에서 rejected 상태로 변화함 + 비동기 처리 결과인 Error 객체를 값으로 가짐

#### 즉, 프로미스는 `비동기 처리 상태`와 `처리 결과`를 관리하는 `객체`다.

# 45-3. 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면, 이에 따른 후속 처리를 해야 함
  - ex ) 프로미스가 fulfilled 상태가 되면 프로미스의 처리 결과를 가지고 무언가를 해야 함
- 이를 위해 프로미스는 후속 메서드 then, catch, finally 를 제공함

#### 프로미스의 `비동기 처리 상태가 변화`하면, `후속 처리 메서드`에 `인수`로 전달한 `콜백 함수`가 선택적으로 호출됨

## 45-3-1. Promise.prototype.then

then 메서드는 두 개의 콜백 함수를 인수로 전달받음

- 첫 번째 콜백 함수는 프로미스가 `fulfilled` 상태(resolve 함수가 호출된 상태) 가 되면 호출됨
  - 이때 콜백 함수는 프로미스의 `비동기 처리 결과`를 인수로 전달받음 (`성공` 처리 콜백 함수)
- 두 번째 콜백 함수는 프로미스가 `rejected` 상태(reject 함수가 호출된 상태) 가 되면 호출됨
  - 이때 콜백 함수는 프로미스의 `에러`를 인수로 전달 받음 (`실패` 처리 콜백 함수)

```javascript
// fulfilled
new Promise(resolve => resolve('fulfilled'))
        .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
        .then(v => console.log(v), e => console.error(e));  // Error: rejected
```

`then 메서드`
  - `언제나 프로미스를 반환`
  - 만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고,
  - 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환


## 45-3-2. Promise.prototype.catch

`catch 메서드`
- 한 개의 콜백 함수를 인수로 전달 받음
- catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출됨
- then(undefined, onRejected) 과 동일하게 동작함
  - so, then 메서드와 마찬가지로 `언제나 프로미스를 반환`


## 45-3-3. Promise.prototype.finally

`finally 메서드`
- 한 개의 콜백 함수를 인수로 전달 받음
- `프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출됨`
- 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용
- `언제나 프로미스를 반환`

# 45-3. 프로미스의 에러 처리

비동기 처리에서 발생한 에러는 then 메서드의 두 번째 콜백 함수로 처리 가능

```javascript
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL 이 지정되었기 때문에 에러 발생
promiseGet(wrongUrl).then(
    res => console.log(res),
    err => console.error(err)    
); // Error: 404
```

비동기 처리에서 발생한 에러는 프로미스의 후속 처리 메서드 catch 를 사용해 처리 가능

```javascript
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL 이 지정되었기 때문에 에러 발생
promiseGet(wrongUrl)
        .then(res => console.log(res))
        .catch(err => console.error(err)); // Error: 404
        
```

메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 좋고 명확함


# 45-5. 프로미스 체이닝

````javascript
const url = 'https://jsonplaceholder.typicode.com';

// id 가 1 인 post 의 userId 를 취득
promiseGet(`${url}/posts/1`)
    // 취득한 post 의 userId 로 user 정보를 취득
    .then(({userId}) => promiseGet(`${url}/users/${userId}`))
    .then(userInfo => console.log(userInfo))
    .catch(err => console.error(err));
````

- 위 예제에서 then -> then -> catch 순서로 후속 처리 메서드를 호출함
- then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하므로, 연속적으로 호출 가능
  - 이를 `프로미스 체이닝(promise channing)` 이라고 함


- 프로미스의 후속 처리 메서드 콟백 함수
  - 프로미스의 비동기 처리 상태가 변경되면 선택적으로 호출됨


| 후속 처리 메서드                              | 콜백 함수의 인수                                                          | 후속 처리 메서드의 반환값                           |
|:---------------------------------------|:-------------------------------------------------------------------|:-----------------------------------------|
| then                                   | promiseGet 함수가 반환한 프로미스가 resolve 한 값(id 가 1인 포스트)                  | 콟백 함수가 반환한 프로미스                          |          
| then                                   | 첫 번째 then 메서드가 반환한 프로미스가 resolve 한 값 (post 의 userId 로 취득한 user 정보) | 콜백 함수가 반환한 값(undefined) 을 resolve 한 프로미스 | 
| catch <br/> * 에러가 발생하지 않으면<br/>호출되지 않음 | promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject 한 값                | 콜백 함수가 반환한 값(undefined) 을 resolve 한 프로미스 |


- then, catch, finally `후속 처리 메서드`
  - `콜백 함수가 반환한 프로미스를 반환`
    - 만약 후속 처리 메서드의 콜백 함수가 프로미스가 아닌 값을 반환하더라도,
    - 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환함



- `프로미스`
  - 프로미스 체이닝을 통해 `비동기 처리 결과를 전달받아 후속 처리`를 함
  - 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬 발생 X
    - but, 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것 X --> 가독성 좋지 않음
      - 이 문제는 ES8 에서 도입된 `async/await` 를 통해 해결
      - `프로미스의 후속 처리 메서드 없이, 마치 동기 처리처럼 프로미스가 처리 결과를 반환`하도록 구현


````javascript
const url = 'https://jsonplaceholder.typicode.com';

(async () => {
    // id 가 1 인 post 의 userId 를 취득
    const { userId } = await promiseGet(`${url}/posts/1`);
    
    // 취득한 post 의 userId 로 user 정보를 취득
    const userInfo = await promiseGet(`${url}/users/${userId}`);
    
    console.log(userInfo);
})();
````

# 45-6. 프로미스의 정적 메서드

Promise
- 주로 생성자 함수로 사용되지만,
- 함수도 객체이므로 메서드를 가질 수 있음
- 5 가지 정적 메서를 제공함

## 45-6-1. Promise.resolve / Promise.reject

- Promise.resolve 와 Promise.reject
  - 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용함

`Promise.resolve` 메서드는 `인수로 전달받은 값을 resolve` 하는 프로미스를 생성함

```javascript
// 배열을 resolve 하는 프로미스를 생성
const resolvePromise = Promise.resolve([1, 2, 3]);
resolvePromise.then(console.log);  // [1, 2, 3]
```

위 예제는 다음 예제와 동일하게 동작함

```javascript
const resolvedPromise = new Promise(resolve => resolve([1, 2, 3]));
resolvePromise.then(console.log);  // [1, 2, 3]
```

`Promise.reject` 메서드는 `인수로 전달받은 값을 reject` 하는 프로미스를 생성함

```javascript
// 에러 객체를 reject 하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error('Error!'));
rejectedPromise.catch(console.log);  // Error: Error!
```

위 예제는 다음 예제와 동일하게 동작함

```javascript
const rejectedPromise = new Promise((_, reject) => reject(new Error('Error!')));
rejectedPromise.catch(console.log);  // Error: Error!
```

## 45-6-2. Promise.all

Promise.all 메서드는` 여러 개의 비동기 처리를 모두 병렬(parallel) 처리`할 때 사용

만약 비동기 처리를 순차적으로 처리할 경우,
- 각각의 비동기 처리는 서로 의존하지 않고 개별적으로 처리하는 경우에 비효율적임
- 즉, 앞선 비동기 처리 결과를 다음 비동기 처리가 사용되지 않는다면, 순차적으로 처리할 필요 X

````javascript
const requestData1 = () =>
    new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
    new Promise(resolve => setTimeout(() => resolve(2), 3000));
const requestData3 = () =>
    new Promise(resolve => setTimeout(() => resolve(3), 3000));

// 세 개의 비동기 처리를 병렬로 처리
Promise.all([requestData1(), requestData2(), requestData3()])
    .then(console.log) // [ 1, 2, 3 ] => 약 3초 소요
    .catch(console.error);
````

`Promise.all 메서드`
- `프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음`
- 전달받은 모든 프로미스가 모두 `fulfilled` 상태가 되면, `모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환함(종료)`
  - so, Promise.all 메서드가 종료하는데 걸리는 시간 : 가장 늦게 fulfilled 상태가 되는 프로미스의 처리 시간보다 조금 더 김
- 인수로 전달받은 배열의 프로미스가 하나라도 `rejected` 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것 기다리지 않고 `즉시 종료`


- 모든 프로미스가 fulfilled 상태가 되면, resolve 된 처리 결과를 모두 배열에 저장해 새로운 프로미스를 반환함
  - 이때 첫 번째 프로미스가 가장 나중에 fulfilled 상태가 되어도,
  - Promise.all 메서드는 첫 번째 프로미스가 resolve 한 처리 결과부터 차례대로 배열에 저장해 그 배열을 resolve 하는 새로운 promise 를 반환함
  - 즉, `처리 순서가 보장됨`


## 45-6-3. Promise.race

Promise.race
- Promise.all 메서드와 동일하게 `프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음`
- Promise.all 메서드처럼 모든 프로미스가 fulfilled 상태가 되는 것을 기다리지 X
- `가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve 하는 새로운 프로미스를 반환함`

```javascript
Promise.race([
    new Promise(resolce => setTimeout(() => resolce(1), 3000)), // 1
    new Promise(resolce => setTimeout(() => resolce(2), 2000)), // 2
    new Promise(resolce => setTimeout(() => resolce(3), 3000)), // 3
])
    .then(console.log) // 3
    .catch(console.log)
```

`Promise.race` 메서드에 전달된 프로미스가 하나라도 `rejected` 상태가 되면, `에러를 reject 하는 새로운 프로미스를 즉시 반환함`

```javascript
Promise.race([
    new Promise(resolce => setTimeout(() => resolce(1), 3000)), // 1
    new Promise(resolce => setTimeout(() => resolce(2), 2000)), // 2
    new Promise(resolce => setTimeout(() => resolce(3), 3000)), // 3
])
    .then(console.log) 
    .catch(console.log);  // Error: Error 3
```

## 45-6-4. Promise.allSettled

`Promise.allSettled 메서드`
- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받음
- 전달받은 프로미스가 모두 `settled` 상태(`비동기 처리가 수행된 상태`, 즉 `fulfilled 또는 rejected 상태`) 가 되면, `처리 결과를 배열로 반환`
- ES11(ECMAScript 2020) 에 도입됨
  - IE 를 제외한 대부분의 모든 브라우저에서 지원함

```javascript
Promise.allSettled([
    new Promise(resolve => setTimeout(() => resolve(1), 2000)), 
    new Promise((_, reject) => setTimeout(() => reject(new Error('Error!')), 1000))
]).then(console.log);

/*
[
    {status: "fulfilled", value: 1},
    {status: "rejected", reason: Error: Error! at <annoymous>:3:54}
] 
*/
```

Promise.allSettled 메서드가 반환한 배열
- `fulfilled 또는 rejected 상태와는 상관없이` Promise.allSettled 메서드가 `전달받은 모든 프로미스들의 처리 결과가 모두 담겨 있음`

### 프로미스의 처리 결과를 나타내는 객체
1. 프로미스가 `fulfilled` 상태인 경우, 비동기 처리 상태를 나타내는 `status` 프로퍼티와 처리 결과를 나타내는 `value` 프로퍼티를 가짐
2. 프로미스가 `rejected` 상태인 경우, 비동기 처리 상태를 나타내는 `status` 프로퍼티와 처리 결과를 나타내는 `reason` 프로퍼티를 가짐


```javascript
[
    // 프로미스가 fulfilled 상태인 경우
    {status: "fulfilled", value: 1},
    // 프로미스가 rejected 상태인 경우
    {status: "rejected", reason: Error: Error! at <annoymous>:3:60}
]
```

# 45-7. 마이크로태스크 큐

```javascript
setTimeout(() => console.log(1), 0);

Promise.resolve()
    .then(() => console.log(2))
    .then(() => console.log(3));
```

- 프로미스의 후속 처리 메서드도 비동기로 동작하므로 1 -> 2 -> 3 순으로 출력될 것처럼 보이지만, `2 -> 3 -> 1` 순으로 출력됨
  - `프로미스의 후속 처리 메서드의 콜백 함수`는 태스크 큐가 아니라 `마이크로 태스크 큐(microtask queue/job queue)` 에 저장되기 때문


- `마이크로태스크 큐`
  - 태스크 큐와 별도의 큐
  - `프로미스의 후속 처리 메서드의 콜백 함수가 임시 저장`됨
  - 그 외의 `비동기 함수의 콜백 함수나 이벤트 핸들러`는 `태스크 큐`에 일시 저장됨

#### 마이크로태스크 큐는 태스킄 큐보다 우선순위가 높다!

즉, 이벤트 루프는 콜 스택이 비면, 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행함

# 45-8. fetch

fetch 함수
- XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API
- XMLHttpRequest 객체보다 사용법이 간단 + 프로미스를 지원 = 비동기 처리를 위한 콜백 패턴의 단점에서 자유로움
  - 비교적 최근에 추가된 Web API 로서 IE 를 제외한 대부분의 모던 브라우저에서 제공됨
- HTTP 요청을 전송할 URL, HTTP 요청 메서드, HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달함

```markdown
const promise = fetch(url [, options])
```

#### fetch 함수는 HTTP 응답을 나타내는 `Response 객체를 래핑한 Promise 객체를 반환`함

```javascript
fetch('https://jsonplaceholder.typicode.com/todos/1')
    .then(response => console.log(response));
```

- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 프로미스를 반환하므로, 
- 후속 처리 메서드 then 을 통해 프로미스가 resolve 한 Response 객체를 전달받을 수 있음


#### Response.prototype
- `Response 객체에 포함되어 있는 HTTP 응답 몸체를 위한 다양한 메서드를 제공`
- ex ) fetch 함수가 반환한 프로미스가 래핑하고 있는 MIME 타입이 application/json 인 HTTP 응답 몸체를 취득하려면
  - `Response.prototype.json 메서드`를 사용함
    - Response.prototype.json 메서드 : Response 객체에서 `HTTP 응답 몸체(response body)` 를 취득하여 `역직렬화`함


```javascript
fetch('https://jsonplaceholder.typicode.com/todos/1')
    // response 는 HTTP 응답을 나타내는 Response 객체다.
    // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화함
    .then(response => response.json())
    // json = 역직렬화된 HTTP 응답 몸체
    .then(json => console.log(json));
    // {userId: 1, id: 1, title: "delectus aut autem". completed: false}
```

fetch 함수를 사용할 때는 에러 처리에 주의해야 함

```javascript
const wrongUrl = 'https://xxx/1';

// 부적절한 URL 이 지정되었기 때문에 404 Not Found 에러가 발생함
fetch(wrongUrl)
    .then(() => console.log('ok'))
    .catch(() => console.log('error'));
```

- 부적절한 URL 이 지정되었기 때문에 404 Not Found 에러가 발생하고
- catch 후속 처리 메서드에 의해 'error' 가 출력될 것처럼 보이지만 'ok' 가 출력됨

#### fetch 함수가 반환하는 프로미스는 기본적으로 `404 Not Found` 나 `500 Internal Server Error` 와 같은 `HTTP 에러`가 발생해도,
#### 에러를 reject 하지 않고 `불리언 타입의 ok 상태를 false 상태로 설정한 Response 객체를 resolve` 한다.
#### `오프라인 등의 네트워크 장애`나 `CORS 에러`에 의해 요청이 완료되지 못한 경우에만 프로미스를 `reject` 한다.

axios
- 모든 HTTP 에러를 reject 하는 프로미스를 반환함 (편리)
- 인터셉터, 요청 설정 등 fetch 보다 다양한 기능을 제공


fetch 함수를 통해 HTTP 요청을 전송하자
- 첫 번째 인수로 HTTP 요청을 전송할 URL
- 두 번째 인수로 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

### GET 요청

```javascript
request.get('https://jsonplaceholder.com')
    .then(response => {
        if (!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```

### POST 요청

```javascript
request.post('https://jsonplaceholder.com', {
    userId: 1,
    title: 'JavaScript',
    completed: false
})
    .then(response => {
        if (!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));
// {userId: 1, title: "JAvaScript, comopleted: false, id: 201}
```

### PATCH 요청

```javascript
request.patch('https://jsonplaceholder.com', {
    completed: true
})
    .then(response => {
        if (!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: true}
```

### DELETE 요청

```javascript
request.delete('https://jsonplaceholder.com')
    .then(response => {
        if (!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));
// {}
```
